### ISSUE TITLE
AuthenticateJWTLocal does not return custom claims

### ISSUE THREAD

**Issue by jp-dakota** [stytchauth/stytch-go#154]
When we use `AuthenticateJWT`, which calls out to Stytch's APIs, a custom [Session](https://github.com/stytchauth/stytch-go/blob/main/stytch/consumer/sessions/types.go#L276) is used, which supports custom claims.

In the local version, the intermediary [Claims](https://github.com/stytchauth/stytch-go/blob/main/stytch/consumer/sessions/types.go#L484) type is used, which does not support custom claims.

**Comment by jeremy-stytch** [comment]
This should be fixed by #164, which just released as [v12.2.1](https://github.com/stytchauth/stytch-go/releases/tag/v12.2.1).

Thank you for reporting this!
