### ISSUE TITLE
all: add context args to all API calls

### ISSUE THREAD

**Issue by josharian** [stytchauth/stytch-go#95]
Since all the API calls block indefinitely, ideally they should all accept a context.Context argument, which would get threaded down to individual http requests, so that we can cancel requests as part of cleanup when our own contexts expire.

This would be a pretty widespread API change, so it'd require a major version bump.

I'm happy to help with the legwork, assuming that the change itself is welcome.

**Comment by austin-stytch** [comment]
Thanks for the suggestion @josharian , and appreciate your patience. The API has been updated to include `context.Context` in v7.0.0
